### ISSUE TITLE
Lambda, Beanstalk, others? - Deploying folders using path_to_code: <folder_name> zips the directory itself rather than contents of the directory

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit-appdev/handel#105]

**Comment by dsw88** [comment]
I believe I've fixed this issue. Your subdirectory shouldn't be getting included anymore in the path. Try removing your ebextension that you had as a workaround and run your deploy again. This time all your files should just be included at the root rather than in a subdirectory.
