### ISSUE TITLE
Lambda - Provide environment variable HANDEL_ENVIRONMENT_NAME

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit-appdev/handel#125]
This is something Beanstalk already has.

Since the keys for Handel-provided environment variables change based on environment, I've seen how this variable is pretty useful in determining where to check for the other variables.

**Comment by dsw88** [comment]
Somehow this got left out of Lambda; it's in the other compute services (ECS, Beanstalk, API Gateway). I'll make sure it gets added.

**Comment by dsw88** [comment]
This should be added for Lambdas. Do a redeploy and you should see the HANDEL_ENVIRONMENT_NAME there.
