### ISSUE TITLE
Lambda - Scheduled function execution

### ISSUE THREAD

**Issue by dsw88** [byu-oit-appdev/handel#62]

**Comment by pauldeden** [comment]
This is the only feature keeping me from trying handel for my https://github.com/byu-oit-appdev/timekeeper-alerter and https://github.com/byu-oit-appdev/ical2timekeeper lambdas

**Comment by pauldeden** [comment]
Allowing the developer in the handel template to specify the lambda event json object for each schedule will be necessary like is done for SAM CF templates.  Here are a [few examples](https://github.com/byu-oit-appdev/weekly-report-sla/blob/master/sam_pre.yml#L35).

**Comment by dsw88** [comment]
@pauldeden You should be able to run a scheduled lambda now with the CloudWatch Events service. See https://github.com/byu-oit-appdev/handel/wiki/CloudWatch-Events for the docs on the new service. It includes an example showing a Lambda being invoked on a schedule.

**Comment by pauldeden** [comment]
Awesome, thanks!  I'll let you know how my handel work goes.
