### ISSUE TITLE
Add the ability to define tags for lambda functions

### ISSUE THREAD

**Issue by pauldeden** [byu-oit-appdev/handel#68]
self explanatory

**Comment by pauldeden** [comment]
necessary for required tagging policy defined at https://byuoit.atlassian.net/wiki/display/OAPP/Tagging

**Comment by dsw88** [comment]
Added support for tagging. See http://handel.readthedocs.io/en/latest/supported-services/lambda.html for information on adding tags to your Lambda. Other services don't support tagging yet, but I've added issues on the roadmap for adding support for the other services.
